FROM alpine:3.18

# Install Bash
RUN apk add --no-cache bash zip openssh-client

# To Build: docker build --pull --rm -f "DockerFile" -t alpine3.18-deploy:latest "."
# To Run: docker run --rm -v ${PWD}:/app -w /app alpine3.18-deploy:latest command here
# To launch a shell inside the container: docker run -i -t --rm -v ${PWD}:/app -w /app alpine3.18-deploy:latest /bin/bash
# To launch a shell inside the container binding port 8000: docker run -i -t --rm -p 8000:8000 -v ${PWD}:/app -w /app alpine3.18-deploy:latest /bin/bash